using Xspec.Assert;
using Xspec.Test.TestData;

namespace Xspec.Test.Given;

public class WhenGivenZipCode : Spec<MyValueTypeModel, MyZipCode>
{
    [Fact]
    public void GivenAutoGeneratedPrimitiveIsRestrictedInt_ThenValueIsUsed()
    {
        Using(A<MyZipCode>).When(_ => _.ZipCode)
            .Then().Result.Is(The<MyZipCode>())
            .And(Result).Primitive.Is().not.LessThan(0).and.LessThan(100_000);
        Specification.Is(
            """
            Using a MyZipCode
            When _.ZipCode
            Then Result is the MyZipCode
              and Result.Primitive is not less than 0
                and less than 100_000
            """);
    }
}